.TH ESCODEGEN "1" "May 2018" "escodegen"
.SH NAME
escodegen \- ECMAScript code generator
.SH SYNOPSIS
.B escodegen
[\fI\,options\/\fR] \fI\,file\/\fR...
.SH DESCRIPTION
.B escodegen
is an ECMAScript (also popularly known as JavaScript) code generator from Mozilla's Parser API AST.
.SH OPTIONS
\fB\-c\fR, \fB\-\-config\fR String
configuration json for escodegen
