.TH ESGENERATE "1" "May 2018" "esgenerate"
.SH NAME
esgenerate \- ECMAScript code generator
.SH SYNOPSIS
.B esgenerate
[\fI\,options\/\fR] \fI\,file\/\fR...
.SH DESCRIPTION
.B esgenerate
is an ECMAScript (also popularly known as JavaScript) code generator from Mozilla's Parser API AST.
.SH OPTIONS
\fB\-c\fR, \fB\-\-config\fR String
configuration json for escodgen
.SH SEEALSO
escodgen(1)
